Compatible with GitLab 6 and GitLab CI 3
* Updated all relevant files to support new versions
  - GitLab 6.0.1
  - GitLab Shell 1.7.1
  - GitLab CI 3.1.0
* Strictly seperated GitLab and GitLab CI
  Now you can install GitLab CI without installing GitLab and GitLab Shell
* Seperated Git and Ruby into own recipes
  Now you can decide if you want to install Git/Ruby from package or from source
* Changed Webserver to be configurable (like database)
* Removed writing of bashrc and placed a script into profile.d instead

diff --git a/templates/default/gitlab_ci.init.erb b/templates/default/gitlab_ci.init.erb
--- a/templates/default/gitlab_ci.init.erb
+++ b/templates/default/gitlab_ci.init.erb
@@ -1,32 +1,31 @@
 #! /bin/bash
 
-# This file was generated by chef for <%= node[:fqdn] %>
-# do not change this file by hand!
-<% app_name = @app_name.gsub(/-/, ' ').split(/ /).map(&:capitalize).join(' ')  %>
-# <%= @app_name %>
+# GITLAB CI
+# Maintainer: @randx
+# App Version: 2.2
 
 ### BEGIN INIT INFO
-# Provides:          <%= app_name %>
+# Provides:          gitlab-ci
 # Required-Start:    $local_fs $remote_fs $network $syslog redis-server
 # Required-Stop:     $local_fs $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: <%= app_name %>
-# Description:       <%= app_name %>
+# Short-Description: GitLab CI
+# Description:       GitLab CI
 ### END INIT INFO
 
 APP_USER="<%= @app_user %>"
 APP_ROOT="<%= @app_home %>"
 DAEMON_OPTS="-C $APP_ROOT/config/puma.rb -e production"
 SOCKET_PATH="$APP_ROOT/tmp/sockets"
-SOCKET_FILE="$SOCKET_PATH/<%= @app_name %>.socket"
+SOCKET_FILE="$SOCKET_PATH/gitlab-ci.socket"
 PID_PATH="$APP_ROOT/tmp/pids"
 WEB_SERVER_PID="$PID_PATH/puma.pid"
 SIDEKIQ_PID="$PID_PATH/sidekiq.pid"
 STOP_SIDEKIQ="RAILS_ENV=production bundle exec rake sidekiq:stop"
 START_SIDEKIQ="RAILS_ENV=production bundle exec rake sidekiq:start"
-NAME="<%= app_name %>"
-DESC="<%= app_name %> service"
+NAME="GitLab CI"
+DESC="Gitlab CI service"
 
 check_pid(){
   if [ -f $WEB_SERVER_PID ]; then
@@ -39,10 +38,6 @@ check_pid(){
   fi
 }
 
-execute() {
-  sudo -u $APP_USER -H bash -l -c "$1"
-}
-
 start() {
   cd $APP_ROOT
   check_pid
@@ -52,9 +47,9 @@ start() {
     exit 1
   else
     if [ `whoami` = root ]; then
-      ! [ -e $SOCKET_FILE ] || execute "rm $SOCKET_FILE"
-      execute "RAILS_ENV=production bundle exec puma $DAEMON_OPTS"
-      execute "mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &"
+      ! [ -e $SOCKET_FILE ] || sudo -u $APP_USER -H bash -l -c  "rm $SOCKET_FILE"
+      sudo -u $APP_USER -H bash -l -c "RAILS_ENV=production bundle exec puma $DAEMON_OPTS"
+      sudo -u $APP_USER -H bash -l -c "mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &"
       echo "$DESC started"
     fi
   fi
@@ -66,8 +61,7 @@ stop() {
   if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
     ## Program is running, stop it.
     kill -QUIT `cat $WEB_SERVER_PID`
-    ! [ -e $SOCKET_FILE ] || execute "rm $SOCKET_FILE"
-    execute "mkdir -p $PID_PATH && $STOP_SIDEKIQ  > /dev/null  2>&1 &"
+    sudo -u $APP_USER -H bash -l -c "mkdir -p $PID_PATH && $STOP_SIDEKIQ  > /dev/null  2>&1 &"
     rm "$WEB_SERVER_PID" >> /dev/null
     echo "$DESC stopped"
   else
@@ -83,13 +77,14 @@ restart() {
   if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
     echo "Restarting $DESC..."
     kill -USR2 `cat $WEB_SERVER_PID`
-    execute "mkdir -p $PID_PATH && $STOP_SIDEKIQ  > /dev/null  2>&1 &"
+    sudo -u $APP_USER -H bash -l -c "mkdir -p $PID_PATH && $STOP_SIDEKIQ  > /dev/null  2>&1 &"
     if [ `whoami` = root ]; then
-      execute "mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &"
+      sudo -u $APP_USER -H bash -l -c "mkdir -p $PID_PATH && $START_SIDEKIQ  > /dev/null  2>&1 &"
     fi
     echo "$DESC restarted."
   else
-    start
+    echo "Error, $NAME not running!"
+    exit 1
   fi
 }
 
@@ -97,7 +92,7 @@ status() {
   cd $APP_ROOT
   check_pid
   if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
-    echo "$DESC / Puma with PID $PID is running."
+    echo "$DESC / Unicorn with PID $PID is running."
     echo "$DESC / Sidekiq with PID $SPID is running."
   else
     echo "$DESC is not running."
